name: Backup

on: push

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/backup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
